### ISSUE TITLE
Issues with cable collisions

### ISSUE THREAD

**Issue by 0auBSQ** [TomKauffeld/GMTK-2021#2]
![graphe3d](https://user-images.githubusercontent.com/58159635/121773677-b7cdcb00-cb7d-11eb-9fd4-cca48f6155b1.jpg)
Would be better to keep simple rectangular collisions to avoid cases like this one

**Comment by TomKauffeld** [comment]
Problem isn't with the collisions, but with the fact you can "teleport" the cable from one side to the other side of the fence.
Further investigation is required.

**Comment by 0auBSQ** [comment]
Fixed... somehow :p
